// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// profile
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';

// stands
export const STANDS_LOADING = 'STANDS_LOADING';
export const GET_PROFILE_STANDS = 'GET_PROFILE_STANDS';
export const GET_STAND = 'GET_STAND';
export const DELETE_STAND = 'DELETE_STAND';

// geolocation
export const USER_POSITION_LOADING = 'USER_POSITION_LOADING';
export const GET_USER_POSITION = 'GET_USER_POSITION';
export const ADDRESS_POSITION_LOADING = 'ADDRESS_POSITION_LOADING';
export const GET_ADDRESS_POSITION = 'GET_ADDRESS_POSITION';

// search
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_GET_RESULTS = 'SEARCH_GET_RESULTS';
